version: 2.1
jobs:
  build:
    docker:

      - image: circleci/php:7.3-fpm
      - image: circleci/mysql:5.7
    environment:
        - APP_DEBUG: true
        - APP_ENV: testing
        - APP_KEY: base64:CxIPfh57UZxLKUojcbA1qc8hHWgR4WCsrdsNG8ibwHE=
        - DB_CONNECTION: circleci
    steps:
      - checkout

      - run:
          name: library_setup 
          command: |
            sudo apt-get update && sudo apt-get install -y libpng-dev libjpeg-dev |
            sudo docker-php-ext-configure gd --with-png-dir=/usr/include --with-jpeg-dir=/usr/include  

      - run: sudo docker-php-ext-configure gd --with-png-dir=/usr/lib/ --with-jpeg-dir=/usr/lib/  --with-gd

      - run: sudo docker-php-ext-install pdo_mysql gd

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "./src/composer.json" }}
            - v1-dependencies-

      - run:
          command: composer install -n --prefer-dist  
          working_directory: ./src

      - save_cache:
          key: v1-dependencies-{{ checksum "./src/composer.json" }}
          paths:
            - ./src/vendor

      - run: 
          command: php artisan migrate  --database=circleci --force
          working_directory: ./src

      - run:
          command: ./vendor/bin/phpunit
          working_directory: ./src


orbs:
  aws-ecr: circleci/aws-ecr@6.5.0
  aws-ecs: circleci/aws-ecs@1.0.4
workflows:
  build_and_deploy:
    jobs:
      - build
      - aws-ecr/build-and-push-image:
          dockerfile: ./docker/nginx/Dockerfile
          path: ./
          name: 'nginx_build'
          repo: '${APP_PREFIX}-nginx'
          requires:
            - build
          filters:
            branches:
              only: master
      - aws-ecr/build-and-push-image:
          dockerfile: ./docker/php-fpm/Dockerfile
          path: ./
          extra-build-args: --target product
          name: 'php_build'
          repo: '${APP_PREFIX}-php'
          requires:
            - build
          filters:
            branches:
              only: master
      - aws-ecs/deploy-service-update:
          name: 'ecs-deploy'
          family: '${APP_PREFIX}-task'
          cluster-name: '${APP_PREFIX}-cluster'
          service-name: '${APP_PREFIX}-service'
          requires:
            - php_build
          filters:
            branches:
              only: master